### ISSUE TITLE
APIドキュメントの規格を用いて書いてほしい

### ISSUE THREAD

**Issue by hanachin** [hanachin/idobata-api-doc#1]
- [API Blueprint - API Documentation with powerful tooling](http://apiblueprint.org/)
- [RAML - RESTful API modeling language](http://raml.org/)

**Comment by niku** [comment]
[GraphQL を用いて書かれた](https://idobata.io/ja/api)ので閉じていいと思いました．
どうですか @hanachin

**Comment by hanachin** [comment]
ありがとうございます。確かにそうですね :crab: 閉じます!!
